version: '3.0'
services:
  valhalla:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # The tile_file must be located in the Dockerfile folder.
        # The tile_file has priority and is used when valid.
        # If the tile_file doesn't exist, the url is used instead.
        # Don't blank out tile_url when you use tile_file and vice versa.
        tile_file: localfile.pbf
        tile_url: https://download.geofabrik.de/europe/croatia-latest.osm.pbf
        # Get correct bounding box from e.g. https://boundingbox.klokantech.com/
        min_x: 13 # -> Croatia | -180 -> World
        min_y: 42 # -> Croatia | -90  -> World
        max_x: 20 # -> Croatia |  180 -> World
        max_y: 47 # -> Croatia |  90  -> World
        build_elevation: "True"
        build_admins: "True"
        build_time_zones: "True"
    ports:
      - "8002:8002"
    volumes:
      - ./conf/:/custom_conf/:ro

